### ISSUE TITLE
Xcode 8 beta 2 support

### ISSUE THREAD

**Issue by JohnEstropia** [vapor/slack-bot#2]
The project (and it's dependencies) currently don't run on the latest Swift 3 build.

**Comment by tanner0101** [comment]
We should probably update straight to Xcode beta 3 while we're at it.

**Comment by JohnEstropia** [comment]
Sounds good :)

**Comment by loganwright** [comment]
Everything's up now for Vapor 0.15 w/ beta2, 3, or 4 and toolchain 07-25 👍

**Comment by JohnEstropia** [comment]
Awesome, thanks!
